### ISSUE TITLE
Any way to escape bbcode tags?

### ISSUE THREAD

**Issue by davidferguson** [JiLiZART/bbob#16]
Is there a way to escape a bbcode tag, with for example a backslash? Say for example I have the following BBCode:

``This is [b]a test[/b] of \[b\]escaping\[/b\] bbcode``, I would want the parser to produce something like the following tree:

```
[
  "This",
  " ",
  "is",
  " ",
  {
    "tag": "b",
    "attrs": {},
    "content": [
      "a",
      " ",
      "test"
    ]
  },
  "of",
  " ",
  "[b]escaping[/b]",
  " ",
  "bbcode"
]
```

Is this possible?

**Comment by JiLiZART** [comment]
Hi! Now it's not possible, but it's not so really hard to implement.

**Comment by davidferguson** [comment]
You'll see I've submitted a PR with a working implementation and tests for this. It introduces an option `enableEscapeTags` which when set, enables the escaping of tags via a backslash. Therefore there is no change in behaviour when this option is not supplied, making it fully backwards compatible.
