### ISSUE TITLE
Warning: Component: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

### ISSUE THREAD

**Issue by GVALFER** [JiLiZART/BBob#180]
**Warning: Component: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.**
    at Component (webpack-internal:///(app-client)/./node_modules/@bbob/react/dist/index.js:1076:26)
    at Parser (webpack-internal:///(app-client)/./src/components/forms/TextEditor/editor/Parser.js:17:11)

After install your library, i get this error.

I am using NextJS. 

`import React from "react";
import BBCode from "@bbob/react";
import presetReact from "@bbob/preset-react";

const plugins = [presetReact()];

function Parser({ text }) {
    return <BBCode plugins={plugins}>{text}</BBCode>;
}

export default Parser;
`

**Comment by JiLiZART** [comment]
Thanks for this issues. I think you use latest version of React. 
But `@bbob/react` compatible with React starting from `15.0` version where `defaultProps` is proper way. 

I think I can remove `defaultProps` in next minor release.

**Comment by RiggerJay** [comment]
any news on this one?  or suggestions how to suppress?

**Comment by JiLiZART** [comment]
I think you can ignore warning. Soon will be released migration to TypeScript and this bug will be fixed
