### ISSUE TITLE
ContextFreeTags are not case insensitive

### ISSUE THREAD

**Issue by Alteras1** [JiLiZART/BBob#231]
contextFreeTags option are not treated case insensitively.

This results in odd scenarios where [code][b]hello world[/b][/code] works, but not [CODE][b]hello world[/b][/CODE] depending on the configured contextFreeTags.

opened PR #230 as fix

**Comment by JiLiZART** [comment]
Fixed in https://github.com/JiLiZART/BBob/pull/230
