### ISSUE TITLE
DOM node created for every word?

### ISSUE THREAD

**Issue by spacemud** [JiLiZART/bbob#24]
Thanks for this! It's really useful.

I'm fairly new to JavaScript/React and was wondering if this was expected behaviour when formatting BBcode. The styling looks perfect but when inspecting I see that a DOM node is created for each word, including whitespace characters. Is this normal or anything to worry about?

![bbcode](https://user-images.githubusercontent.com/739977/59841312-985f8700-9343-11e9-86bb-a142b7247a16.PNG)

produces

![dom](https://user-images.githubusercontent.com/739977/59841338-a4e3df80-9343-11e9-90db-7fb67e17f32c.png)

Cheers!

**Comment by JiLiZART** [comment]
BBCode AST represented as space-separated words and objects of tags. So yes, it is normal.

**Comment by spacemud** [comment]
Thank you!
