### ISSUE TITLE
img tag cannot be parsed

### ISSUE THREAD

**Issue by corn-snake** [JiLiZART/BBob#254]
As title implies, adding any img tag will produce an error.
![image](https://github.com/user-attachments/assets/67ccc857-3b30-44c4-b2c8-8f23cd133121)

Behaviour arises immediately upon typing a 'g' after `[im` and before `]`
![image](https://github.com/user-attachments/assets/50de17e8-ff98-4030-b6f5-983044cf47be)

**Comment by JiLiZART** [comment]
Looks like bug. Will be fixed soon

**Comment by JiLiZART** [comment]
My investigation revealed that esm.sh has caching issues. esm.sh is used to import modules in the demo.

```js
/* esm.sh - @bbob/preset-html5@4.1.1 */
import "/v135/@bbob/preset@3.0.2/es2022/preset.mjs";
import "/v135/@bbob/plugin-helper@3.0.2/es2022/plugin-helper.mjs";
export * from "/v135/@bbob/preset-html5@4.1.1/es2022/preset-html5.mjs";
export { default } from "/v135/@bbob/preset-html5@4.1.1/es2022/preset-html5.mjs";
```

It seems that esm.sh incorrectly pointed to version 3.0.2 of @bbob/preset while importing @bbob/preset-html5@4.1.1.

I will look for an alternative service to handle ESM imports in the demo.

All tests that were causing the demo to break are now passing: https://github.com/JiLiZART/BBob/pull/263.
