### ISSUE TITLE
caseFreeTags does not work with typescript and react

### ISSUE THREAD

**Issue by garyb01** [JiLiZART/BBob#266]
"version": "4.1.1"

caseFreeTags seems to be missing 

![image](https://github.com/user-attachments/assets/8b69fd40-5b90-48da-861d-4c1e320c7662)

**Comment by JiLiZART** [comment]
Seems to some bug with `npm publish` on `npm` package no any changes for types

**Comment by JiLiZART** [comment]
Fixed in `@bbob/react@4.2.0`
