### ISSUE TITLE
Bb-code url is incorrectly converted if the value of the attribute href is not in quotes and there are parameters in the link

### ISSUE THREAD

**Issue by gnvcor** [JiLiZART/bbob#36]
From this bb-code: `[url href=https://www.google.com?params=123]google[/url]` I expect to receive a link of the form: `<a href="https://www.google.com?params=123">google</a>`.
But I get: `<a href="" https://www.google.com?params="123">google</a>`.

**Comment by anvu69** [comment]
Same issue!
My BBCode: `[url]http://dantri.com.vn/o-to-xe-may/oto-mien-thue-do-bo-ve-viet-nam-tap-ket-kin-cang-cho-lan-banh-20180724072628474.htm[/url]`
And i receive tag: `<a >http://dantri.com.vn/o-to-xe-may/oto-mien-thue-do-bo-ve-viet-nam-tap-ket-kin-cang-cho-lan-banh-20180724072628474.htm</a>` without `href` attrs.

Here is my code:
```
import bbob from '@bbob/core'
import { createPreset } from '@bbob/preset'
import { render } from '@bbob/html'
import _ from 'lodash'

const reduceAttr = (attrs) => {
  return _.reduce(
    attrs,
    (result, value, key) => {
      (result['attr'] || (result['attr'] = [])).push(value)
      return result.attr
    },
    {}
  )
}

const preset = createPreset({
  url: (node, { render }) => {
    return {
        tag: 'a',
        attrs: {
          href: reduceAttr(node.attrs) !== {}
            ? reduceAttr(node.attrs)[0]
            : render(node.content),
        },
        content: node.content
      }
  }
})

export default {
  convertBBCode (content) {
    if (content) {
      const result = bbob(preset()).process(content, { render }).html.replace(/(?:\r\n|\r|\n)/g, '<br>')
      return result
    } else {
      return ''
    }
  }
}
```

**Comment by JiLiZART** [comment]
Thanks for reporting! I take a look on this problem soon.
PS: You can use 
```js
import BBCode from '@bbob/react/es/Component'
```
instead of using `html-react-parser`

**Comment by ironsm4sh** [comment]
I have a similar problem.
From the readme at  [bbob-parser](https://github.com/JiLiZART/bbob/tree/master/packages/bbob-parser). trying the example will parse into
![image](https://user-images.githubusercontent.com/23172578/75378380-d8fca080-58d3-11ea-96fa-8dc0e08790e8.png)
instead of
```
[
    {
        "tag": "url",
        "attrs": {
            "url": "https://github.com"
        },
        "content": ["hello", " ", "world!"]
    }
]
```
The URL attribute is nowhere to be found, and a new attribute with the name of the url has appeared.
