### ISSUE TITLE
[question] Is it possible to pass Vue component to render tag's content?

### ISSUE THREAD

**Issue by arkhamvm** [JiLiZART/bbob#37]
Hi. I wish to render some custom bb-tag with custom vue component.
Something like this:
```typescript
const myPreset = BbobPresetHTML5.extend((tags: any) => {
  tags.br = () => ({
    tag: 'br',
    attrs: {},
    content: MyJuicyBrComponent({node.attrs}), // Doesn't sure about call syntax, etc
  });    

  return tags;
});
```

**Comment by JiLiZART** [comment]
Currently not possible to integrate parser with Vue Components, but I have plans to do Vue support in the near future.

You can try to look at 
https://github.com/JiLiZART/bbob/blob/master/packages/bbob-react/src/render.js
and do your realization for Vue
