### ISSUE TITLE
Custom bbcodes and list of all available default bbcodes

### ISSUE THREAD

**Issue by TomokoOG** [JiLiZART/bbob#45]
Hi,

I have two questions: How/where could I add custom bbcodes for the parser? And where do I find all supported bb-tags by default?

Thanks!

**Comment by JiLiZART** [comment]
Hi! BB codes are defined by presets https://github.com/JiLiZART/bbob#html-preset
You can create your own preset or extend existing.
Default html5 preset defines processing for `b, i, u, s, url, img, quote, code, style, list, *text`. You can see it here https://github.com/JiLiZART/bbob/blob/master/packages/bbob-preset-html5/src/defaultTags.js#L63

**Comment by TomokoOG** [comment]
Thank you
