### ISSUE TITLE
Would-be attributes on invalid tags being eaten during parse

### ISSUE THREAD

**Issue by ottworks** [JiLiZART/bbob#54]
With onlyAllowTags set to ['b', 'i', 'u'], this happens:

Input: `hello [blah foo="bar"]world[/blah]`

Output: `hello [blah]world[/blah]`

It's still returned as a string in the AST, but there's some sort of pre-processing going on that strips out the would-be attributes.

Repro: https://jsfiddle.net/6acujnf5/3/

**Comment by JiLiZART** [comment]
Thanks for reporting, kinda token to string function fails :(

**Comment by JiLiZART** [comment]
I deploy fix for this problem in about 2-3 days

**Comment by JiLiZART** [comment]
Good news! Problem solved. I deploy release soon.
