### ISSUE TITLE
Javascript injection in default html mode

### ISSUE THREAD

**Issue by 12Me21** [JiLiZART/bbob#66]
`[url]javascript:alert("hello")[/url]`
Need to filter out `javascript:` links

**Comment by JiLiZART** [comment]
Wow. Thanks for the report!

**Comment by AiAe** [comment]
Im facing the same issue with `[span onclick=javascript:alert(1)]red[/span]`.
Any date when new release with this fix?

**Comment by JiLiZART** [comment]
About few days

**Comment by JiLiZART** [comment]
2.5.7 with fixes released https://github.com/JiLiZART/bbob/releases/tag/v2.5.7

**Comment by AiAe** [comment]
@JiLiZART Hello again, I was looking at what u changed and ```replace('javascript:', 'javascript%3A')``` this wont solve the problem, because I managed to get it working again with ```[span onclick=javaSCRIPT:alert(1)]red[/span]```.

**Comment by JiLiZART** [comment]
Oh. I release fix soon (

**Comment by AiAe** [comment]
Also wanted to add this one ```[span onmouseover="alert(document.cookie)"]red[/span]```
I think its better of if you just blacklist all possible "on" events.
https://www.w3schools.com/tags/ref_eventattributes.asp

**Comment by JiLiZART** [comment]
https://github.com/JiLiZART/bbob/releases/tag/v2.5.8 now? I didn't add whole on events, cuz it's bloat for this small library
