### ISSUE TITLE
tag [COLOR="#ff0000"] to  bad html <color #ff0000="#ff0000">

### ISSUE THREAD

**Issue by gg1971** [JiLiZART/bbob#71]
`[COLOR="#ff0000"]text color red [/COLOR]`

now with **presetHTML5** parse like this:

`[{"tag":"color","attrs":{"#ff0000":"#ff0000"},"content":["text"," ","color"," ","red"]}]`

`<color #ff0000="#ff0000">text color red</color>`

how to get the correct code:

`<span style="color:#ff0000">text color red</span>`

???

**Comment by JiLiZART** [comment]
Hello! color tag is not defined in html5 preset (i think i need include this).
But you can define tag manually for yourself.
I paste example later.

**Comment by JiLiZART** [comment]
So, you can easily extend HTML5 preset like this
```js
import bbobHTML from '@bbob/html'
import presetHTML5 from '@bbob/preset-html5'
import { getUniqAttr } from '@bbob/plugin-helper';

const myPreset = presetHTML5.extend((tags) => ({
  ...tags,
  color: node => ({
    tag: 'color',
    attrs: {
      style: `color: ${getUniqAttr(node.attrs)}`
    },
    content: node.content
  })
}))

const processed = bbobHTML(`[COLOR="#ff0000"]text color red [/COLOR]`, myPreset())
// <span style="color:#ff0000">text color red</span>
```

**Comment by gg1971** [comment]
It works!

This is of course "magic", but the main thing is that it worked on the mixture of html + bbcode that falls from the Bitrix24 fields

Thanks a lot for the detailed answer.

**Comment by JiLiZART** [comment]
Anyway I will add color tag to HTML5 preset. This is a temporary fix :)
