### ISSUE TITLE
Cannot gracefully handle parser error with onError option or try-catch

### ISSUE THREAD

**Issue by cheryllium** [JiLiZART/bbob#73]
First off; thank you for the great library! It's been a pleasure to work with so far. 

This issue pertains to the React component using the React presets. I am experiencing a runtime error when specific (not all) improper BBCode is passed to the parser, and am unable to gracefully handle the error using onError or try-catch block. I've created a sandbox to illustrate the issue. 

**Sandbox:** https://codesandbox.io/s/purple-cloud-k8fjl?file=/src/index.js 
In this sandbox, I'm using BBCode component in React to render the BBCode `[b]Testing[/b][hr]`.

**Expected behavior:** It should process the `[b]Testing[/b]` and leave the problematic `[hr]` unprocessed. So I expect it to render the following: **Testing**[hr]

It should also either trigger an `onError()` call, or the code in the `catch` block of the try-catch. Ideally we want it handled in `onError()`, but I included the try-catch in this sandbox because it's weird that the try-catch does not catch it. Maybe that can indicate something about the cause of the problem.

**Actual behavior:** Neither the `onError()` function nor the `catch` block are called. The application crashes with a runtime error. The specific error depends on what specifically broke the parser. In my example I use `"[hr]"` and it throws: 
```
Invariant Violation
hr is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.
    in hr (created by Component)
    in span (created by Component)
    in Component (at src/index.js:10)
    in App (at src/index.js:25)
```

`[hr]` is not the only tag that causes this; it also breaks on `[br]` and `[col]`, so it seems to be a special case and there may be other cases. It does not break on *all* improper BBCode but I am not sure what the conditions are that trigger this.

It is possible this is not an issue with bbob but an error in my own code; if so I would be grateful for any help with what I did wrong, and how to properly handle it to get the behavior I want :) 

Thank you again!

**Comment by JiLiZART** [comment]
First of all, thank you, for good and informative issue :) 
I will try do my best to help you :)

I looked at your example, it's seems to be that tag `col` transforms to `<col>` JSX tag, and React suppose to think that you need `</col>`. 
It's may be problem in `bbob-react` package. I will soon dive deep and fix this.

**Comment by cheryllium** [comment]
Oh whoops - I meant to write `[hr]` in the sandbox. Fixed! (Not that it matters much) 

I think you are right about what the error means, and that the `[hr]` and `[br]` examples also have the same root cause. Thank you so much for taking a look, and for your work on this package!

**Comment by JiLiZART** [comment]
Now all works https://codesandbox.io/s/jolly-lewin-zu2z9?file=/src/index.js

**Comment by cheryllium** [comment]
@JiLiZART Thank you so much for the prompt fix! It's very appreciated.

Unfortunately, it is still not catching all errors. I just discovered a new one: if you change `[hr]` to `[hr ]` (add a space within the tag, rendering it invalid), it throws an `InvalidCharacterError: String contains an invalid character` which is not caught by `onError()` or `try.. catch...`

Sandbox here: https://codesandbox.io/s/cool-jennings-eiohc 
(Or you can add the space in your own sandbox - it is identical)

Expected behavior would be for it to output `[hr ]` literally (since it is not a valid tag, we just want to write what the user input exactly)

Thank you again (and sorry I did not see this sooner, I will check my notification settings...)

**Comment by cheryllium** [comment]
Do you have any insight as to why the `try... catch...` block is not catching any of these errors? I thought it should since the errors originate from within the `try` block

**Comment by cheryllium** [comment]
For that error, I think it is due to trying to set an attribute with invalid characters in the attribute name or value. It may be fixable in the parser by adding a check for invalid characters, and leave unparsed if so. 

I'm not able to pinpoint exactly where to do this in bbob code, because the debugger's traceback doesn't go back that far. I think the reason this is not calling `onError()` is because there was no error in bbob; bbob produced JSX output, and the error is being thrown by React's render function since some JSX contains invalid attributes.

Would you like me to create a separate, new issue about this?

**Comment by JiLiZART** [comment]
Yes, you right. Error occurs in React JSX. So it can be fixed in bbob-react package. (escape invalid chars, trim tag names, etc)
