### ISSUE TITLE
Ordered lists

### ISSUE THREAD

**Issue by arkhamvm** [JiLiZART/bbob#8]
Hi.
`[list]` tag with order attribute (`1`, `A`, `a`, `I`, `i`) should be converted to `ol` instead of `ul`.

![screenshot_20190304_170129](https://user-images.githubusercontent.com/9816112/53716149-acb86a80-3e9f-11e9-9433-408fdfcfdc70.png)

For example:
```
[list] // <ul>
[list=1] // <ol type="1">
[list=A] // <ol type="A">
```

**Comment by JiLiZART** [comment]
Hi @arkhamvm you can extend basic list behavior in your custom preset like this
```
import presetHTML5 from '@bbob/preset-html5';

const getUniqAttr = attrs => Object
  .keys(attrs)
  .reduce((res, key) => (attrs[key] === key ? attrs[key] : null), null);

export default presetHTML5.extend(tags => ({
  ...tags,
  list:(node, ...args) => ({
    ...tags.list(node, ...args),
    tag: getUniqAttr(node.attrs) ? 'ol' : 'ul'
  }),
}));
```

Is there any spec for list types in BBCode?

**Comment by arkhamvm** [comment]
@JiLiZART is `phpbb` spec is valuable example? https://www.phpbb.com/community/help/bbcode#f3r1

**Comment by arkhamvm** [comment]
@JiLiZART sorry for annoying, are you going to implement it? Proposed solution doesn't looks good enough.

**Comment by JiLiZART** [comment]
@arkhamvm yea, a bit later
